import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen grid grid-rows-[auto_1fr_auto]`}
      >
        <header>
          <h1 className="text-center text-4xl font-semibold py-6">
            The Wizard of Web
          </h1>
          <nav className="flex justify-center gap-6 border-b border-t text-l py-4">
            <Link href="/">Hjem</Link>
            <Link href="/faginnhold">Faginnhold</Link>
            <Link href="/oppgaver">Oppgaver</Link>
          </nav>
        </header>
        <main className="px-4 md:px-8 py-8 mx-auto max-w-5xl w-full">
          {children}
        </main>
        <footer className="text-center">
          <p>© 2025 The Wizard of Web</p>
          <p>Created by Colleen, Roman, and Luna</p>
        </footer>
      </body>
    </html>
  );
}
